package myInterpreter;

enum TokenType {
	
	COMMA, DOT, LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACKET, RIGHT_BRACKET,
	
	ASSIGNMENT_OPERATOR, PLUS_OPERATOR, SUBTRACT_OPERATOR, MULTIPLY_OPERATOR, DIVIDE_OPERATOR,

	LESSTHAN_OPERATOR, LESSTHAN_EQUAL_OPERATOR, GREATERTHAN_OPERATOR, GREATERTHAN_EQUAL_OPERATOR, EQUALS_OPERATOR, NOT_EQUALS_OPERATOR,

	IDENTIFIER, INTEGER_LITERAL, STRING_LITERAL,
	
	EOF,

	// Keywords.
	SPECIFICATIONS, SYMBOL, FORWARD, REFERENCES, FUNCTION, POINTER, ARRAY, TYPE, STRUCT, INTEGER, ENUM, GLOBAL, DECLARATIONS, IMPLEMENTATIONS, MAIN, PARAMETERS, CONSTANT, BEGIN, ENDFUN, IF, THEN, ELSE, ENDIF, REPEAT, UNTIL, ENDREPEAT, DISPLAY, SET, RETURN, VARIABLES, DEFINE, EXIT, IMPORT, DO, TO, CONSTANTS
}
